/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as SuccessStoriesRouteImport } from './routes/success-stories'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LiveClassesRouteImport } from './routes/live-classes'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BookDemoRouteImport } from './routes/book-demo'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeachersSlugRouteImport } from './routes/teachers.$slug'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveClassesRoute = LiveClassesRouteImport.update({
  id: '/live-classes',
  path: '/live-classes',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BookDemoRoute = BookDemoRouteImport.update({
  id: '/book-demo',
  path: '/book-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersSlugRoute = TeachersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TeachersRoute,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursesRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book-demo': typeof BookDemoRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/live-classes': typeof LiveClassesRoute
  '/privacy': typeof PrivacyRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/teachers': typeof TeachersRouteWithChildren
  '/terms': typeof TermsRoute
  '/waitlist': typeof WaitlistRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/teachers/$slug': typeof TeachersSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book-demo': typeof BookDemoRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/live-classes': typeof LiveClassesRoute
  '/privacy': typeof PrivacyRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/teachers': typeof TeachersRouteWithChildren
  '/terms': typeof TermsRoute
  '/waitlist': typeof WaitlistRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/teachers/$slug': typeof TeachersSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book-demo': typeof BookDemoRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/live-classes': typeof LiveClassesRoute
  '/privacy': typeof PrivacyRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/teachers': typeof TeachersRouteWithChildren
  '/terms': typeof TermsRoute
  '/waitlist': typeof WaitlistRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/teachers/$slug': typeof TeachersSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/book-demo'
    | '/careers'
    | '/contact'
    | '/courses'
    | '/live-classes'
    | '/privacy'
    | '/success-stories'
    | '/teachers'
    | '/terms'
    | '/waitlist'
    | '/admin'
    | '/courses/$slug'
    | '/teachers/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/book-demo'
    | '/careers'
    | '/contact'
    | '/courses'
    | '/live-classes'
    | '/privacy'
    | '/success-stories'
    | '/teachers'
    | '/terms'
    | '/waitlist'
    | '/admin'
    | '/courses/$slug'
    | '/teachers/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/book-demo'
    | '/careers'
    | '/contact'
    | '/courses'
    | '/live-classes'
    | '/privacy'
    | '/success-stories'
    | '/teachers'
    | '/terms'
    | '/waitlist'
    | '/_authenticated/admin'
    | '/courses/$slug'
    | '/teachers/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BookDemoRoute: typeof BookDemoRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  LiveClassesRoute: typeof LiveClassesRoute
  PrivacyRoute: typeof PrivacyRoute
  SuccessStoriesRoute: typeof SuccessStoriesRoute
  TeachersRoute: typeof TeachersRouteWithChildren
  TermsRoute: typeof TermsRoute
  WaitlistRoute: typeof WaitlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-classes': {
      id: '/live-classes'
      path: '/live-classes'
      fullPath: '/live-classes'
      preLoaderRoute: typeof LiveClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-demo': {
      id: '/book-demo'
      path: '/book-demo'
      fullPath: '/book-demo'
      preLoaderRoute: typeof BookDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/$slug': {
      id: '/teachers/$slug'
      path: '/$slug'
      fullPath: '/teachers/$slug'
      preLoaderRoute: typeof TeachersSlugRouteImport
      parentRoute: typeof TeachersRoute
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface CoursesRouteChildren {
  CoursesSlugRoute: typeof CoursesSlugRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSlugRoute: CoursesSlugRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface TeachersRouteChildren {
  TeachersSlugRoute: typeof TeachersSlugRoute
}

const TeachersRouteChildren: TeachersRouteChildren = {
  TeachersSlugRoute: TeachersSlugRoute,
}

const TeachersRouteWithChildren = TeachersRoute._addFileChildren(
  TeachersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BookDemoRoute: BookDemoRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRouteWithChildren,
  LiveClassesRoute: LiveClassesRoute,
  PrivacyRoute: PrivacyRoute,
  SuccessStoriesRoute: SuccessStoriesRoute,
  TeachersRoute: TeachersRouteWithChildren,
  TermsRoute: TermsRoute,
  WaitlistRoute: WaitlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
